hs_media_website/hs_media_website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),

    # Login and Logout
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='commons/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),

    # Change Password
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='commons/change-password.html',
            success_url = '/'
        ),
        name='change_password'
    ),

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='commons/password-reset/password_reset.html',
             subject_template_name='commons/password-reset/password_reset_subject.txt',
             email_template_name='commons/password-reset/password_reset_email.html',
             success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='commons/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='commons/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='commons/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

hs_media_website/website/urls.py
from django.urls import path
from website.views import SignUpView, ProfileView,HomeView
from website import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path("contact",views.contact, name='contact'),
    path('startcontract', views.UploadFile, name='startcontract'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hs_media_website/website/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class SingletonModel(models.Model):
    class Meta:
        abstract = True


class Logo(SingletonModel):
    image = models.ImageField(upload_to='logos/')

    def save(self, *args, **kwargs):
        self.pk = 1
        super(Logo, self).save(*args, **kwargs)

    def __str__(self):
        return f"Logo {self.pk}"

class StratContract1(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=120)
    file = models.FileField(
        blank=True, null=True, upload_to="documents/", default=False
    )
    desc = models.TextField()
    price = models.FloatField()
    phone = models.CharField(max_length=100)

    def __str__(self):
        return self.user


class Contact1(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField(max_length=120)
    phone = models.CharField(max_length=120)
    desc = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.name

hs_media_website/website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import StratContract1


# Sign Up Form
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional")
    last_name = forms.CharField(max_length=30, required=False, help_text="Optional")
    email = forms.EmailField(max_length=254, help_text="Enter a valid email address")

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.TextInput(attrs={"class": "form-control"}),
            "password2": forms.TextInput(attrs={"class": "form-control"}),
        }


# Profile Form
class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]





class StartContractForm(forms.ModelForm):
    class Meta:
        model = StratContract1
        fields = "__all__"
        exclude = ["user"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Check if 'user' is present in the form
        if 'user' in self.fields:
            self.fields['user'].widget = forms.HiddenInput()  # Hide the user field in the form
            self.fields['user'].initial = self.instance.user

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.instance.user
        if commit:
            instance.save()
        return instance

hs_media_website/templates/base.html
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        {% block css %} {% endblock css %}
    </head>
    <body>
        <!-- <h1>Built-In User Registeration / Authentication App</h1> -->

        {% block content %} {% endblock content %}

        {% block javascript %} {% endblock javascript %}
    </body>
</html>

hs_media_website/templates/contact.html
{% load static %}
{% block title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{% endblock title %}

{% block body %}
<div>
    <img src="{{ logo.image.url }}" class="rounded mx-auto d-block" alt="...">
</div>
<div class="container  py-4">
    <h1 class="text-center text-danger">Enter Your Query And Reason To Contact Us:</h1>
    <div class="card shadow m-5">
        <div class="card-body">
            <h5 class="p-2 text-danger " style="bordder-bottom : 2x solid orange">Contact Form:</h5>
    
        </div>
    </div>
    <form method="post" action="">
    {% csrf_token %}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control "  id="name" name="name" placeholder="Enter your Name">
        </div>

        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control   " id="email" name="email" placeholder="Enter Your Email">
        </div>
        
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <input type="phone" class="form-control   " id="phone" name="phone" placeholder="Enter Your Phone Number">
        </div>      
        
        <div class="form-group">
            <label for="desc">Reason To Contact Us...</label>
            <textarea class="form-control   " id="desc" rows="3" name="desc"></textarea>
        </div>
        
        <div class="col-md-12 text-center text-danger">
            <button type="submit" class="btn btn-outline-danger my-4 text-center">Contact</button>
            <a href="{% url 'home' %}"><button type="button" class="btn btn-outline-danger my-4">Home</button></a>
        </div>
    </form>
    
</div>
{% endblock body %}

hs_media_website/templates/upload.html
{% load static %}
{% block title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{% endblock title %}

{% block body %}
<div>
    <img src="{{ logo.image.url }}" class="rounded mx-auto d-block" alt="...">
</div>

<div class="card shadow m-5">
    <div class="card-body">
        <h5 class="p-2 text-danger " style="bordder-bottom : 2x solid orange">Contract Details:</h5>

    </div>

</div>
<div class="container  py-4">
    <form method='post' class="form-group" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
        
        </div>
          
           <div class="form-group">
            <label for="id_name">Name:</label>
    <input type="text"  class="form-control " name="name" maxlength="100" required id="id_name">
        </div>
        <div class="form-group">
            <label for="id_email">Email:</label>
            <input type="email"  class="form-control is-invalid " name="email" maxlength="120" required id="id_email">
        </div>
        <div class="form-group">
            <label for="id_file">File:</label>
    <input type="file"  class="form-control " name="file" id="id_file" multipart>
        </div>
        <div class="form-group">
            <label for="id_desc">Desc:</label>
            <textarea name="desc"  class="form-control " cols="40" rows="10" required id="id_desc">
        </textarea>
        </div>
        <div class="form-group">
            <label for="id_price">Price:</label>
            <input type="number"  class="form-control " name="price" step="any" required id="id_price">
            
        </div>
        <div class="form-group">
            <label for="id_phone">Phone:</label>
    <input type="text" name="phone"  class="form-control " maxlength="100" required id="id_phone">
            
        </div>
        
       

<div class="col-md-12 text-center text-danger">
    <button type="submit" class="btn btn-outline-danger my-4 text-center">Submit</button><br>
   
    </div>

    </form>
    {% endblock body %}

    
</html>